### ISSUE TITLE
Markbot issue?

### ISSUE THREAD

**Issue by jud3bl4nk** [jud3bl4nk/different-crops-same-image#1]
Code is up to date but markbot is saying it is incorrect.
Thanks!
@charlie-quinn
*addendum: Hi i forgot to tag you, my bad. Thanks for your patience

**Comment by charlie-quinn** [comment]
- [ ] add `.push-1-8` to your `<h1>`
- [ ] add `.push-1-2` to your `<p>`

👌

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by jud3bl4nk** [comment]
Hi,
So sorry - I've been out of the country and forgot my github log in.
Thanks!
